vich_uploader:
    db_driver: orm

    mappings:
        nba_teams_logos:
            uri_prefix: /uploads/nba-teams-logos
            upload_destination: '%kernel.project_dir%/public/uploads/nba-teams-logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
